### ISSUE TITLE
Issue running file

### ISSUE THREAD

**Issue by Lukeghenco** [learn-co-curriculum/ruby-object-attrs-readme#16]
When I create my person.rb file, and I use the class Person with this:

kanye = Person.new("Kanye")

kanye.name
  => "Kanye"

kanye.name = "Yeezy"
kanye.name
  => "Yeezy"

I get this error when I run it as $ ruby person.rb :

person.rb:13:in `initialize': wrong number of arguments (1 for 0) (ArgumentError)
    from person.rb:13:in`new'
    from person.rb:13:in `<main>'

I think there might be a typo in the lesson, or something else needs to be explained. I know you can do that with initializing, but that is taught later.

Thanks,
Luke

**Comment by AnnJohn** [comment]
@MsUzoAgu the other issues here might also be addressing the same problem
