### ISSUE TITLE
The last example doesn't work entirely

### ISSUE THREAD

**Issue by pletcher** [learn-co-curriculum/ruby-object-attrs-readme#20]
Even when we abstract `@first_name` and `@last_name` behind `#name=`, Kanye can't be referred to as _just_ `"Yeezy"` -- at best, he'll be `"Yeezy "` because of how the `#name` getter works.

I'ma let you finish, but we should at least point this out to students.

**Comment by alexgriff** [comment]
@pletcher I see how this example is kind of weird. I believe the `#name` getter would return "Yeezy Yeezy" based on the way the `#name=` setter is designed to take a two-word string.  For the last example, do you think that `#initialize` should take one argument and split the string in two like the setter method does (or vice versa, `#name=` could take two arguments to be consistent with `#initialize`)? And then make note that Mr. West would have to go by "Yeezus West" to fit the two arg requirement... Or should I just make note of the little bit of weirdness here as an aside?

**Comment by pletcher** [comment]
Yep, it would be `"Yeezy Yeezy"` if set with `"Yeezy"`; and in the initializer, if called like `Person.new("Yeezy", "")`, the best we could get is still `"Yeezy "`.

>  For the last example, do you think that #initialize should take one argument and split the string in two like the setter method does (or vice versa, #name= could take two arguments to be consistent with #initialize)?

Yes, either way -- I think it would be much clearer if `#initialize` and `#name=` worked the same way.

> And then make note that Mr. West would have to go by "Yeezus West" to fit the two arg requirement... Or should I just make note of the little bit of weirdness here as an aside?

So we could define the `#name` getter to return, e.g., `"#{@first_name} #{@last_name}".strip` -- a simple fix that'd clear up most use cases.

Aside: I guess the other thing is that names are actually _really_ hard. The first name, last name thing only makes sense for some portion (almost certainly a minority) of the global population. One potential workaround is to use splat params (`*args`), something like `def initialize(first_name, *other_names)` -- then `#name` would look like

``` ruby
def name
  "#{@first_name} #{@other_names.join(" ")}".strip
end
```

But it's probably too early in the curriculum for something like that.
