### ISSUE TITLE
example does not work

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/ruby-object-attrs-readme#23]
# given the method:

class Person 
  def initialize(first_name, last_name)
    @first_name = first_name
    @last_name = last_name
  end

  def name=(first_name, last_name)
    @first_name = first_name
    @last_name = last_name
  end

  def name
    "#{@first_name} #{@last_name}".strip
  end
end
# with the input

kanye = Person.new("Kanye", "West")
# kanye.name will return "Kanye West" like it should
# but then the example at the bottom

kanye.name = "Yeezy", ""
# or my own examples

kanye.name = "Yeezy", "Kardashian"
kanye.name= "Yeezy", ""
kanye.name= "Yeezy", "Kardashian"
kanye.name = ("Yeezy", "")
kanye.name = ("Yeezy", "Kardashian")
kanye.name= ("Yeezy", "")
kanye.name= ("Yeezy", "Kardashian")
# all return syntax errors
# it's really difficult to grasp concepts when the examples don't work

**Comment by AnnJohn** [comment]
hi @StevenNunez can you look into this?

**Comment by octosteve** [comment]
@AnnJohn @pletcher https://github.com/learn-co-curriculum/ruby-object-attrs-readme/pull/24
Setters only take 1 argument, so I passed in a `full_name` string and split it. Is this level appropriate at this point?

**Comment by pletcher** [comment]
Yep, `split` and `strip`.

...

...

Ruby innuendo?

**Comment by ghost** [comment]
@AnnJohn @pletcher @StevenNunez thanks everybody!
