### ISSUE TITLE
Introducing binding.pry with no explanation

### ISSUE THREAD

**Issue by julianjohannesen** [learn-co-curriculum/ruby-object-attrs-readme#34]
This lesson mentions binding.pry with no explanation of what that is.

**Comment by drakeltheryuujin** [comment]
Hi @julianjohannesen, 

Thank you for spotting this issue and providing feedback.

We have updated the materials and believe both issues have been resolved for this lesson. We apologize for any confusion this may have caused, but thank you for helping us ensure that others may not face the same struggles.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
