### ISSUE TITLE
Initializer method is discussed too early

### ISSUE THREAD

**Issue by AnnJohn** [learn-co-curriculum/ruby-object-attrs-readme#5]
for Learn Qualifying Track- this lesson discusses initializers which aren't discussed until the following lesson. Remove and adjust the content.

**Comment by dfenjves** [comment]
Agree with Ann here.

**Comment by sammarcus** [comment]
Came here to say the same :) :raising_hand:

**Comment by jmburges** [comment]
agreed. yank it
